In [1]:
import pandas as pd

In [7]:
df=pd.DataFrame([[101,'a',10000],[102,'b',14000],[103,'c',14000]],columns=['ID','NAme','sal'])
df

    ID NAme    sal
0  101    a  10000
1  102    b  14000
2  103    c  14000

In [9]:
df.set_index('ID')

    NAme    sal
ID
101    a  10000
102    b  14000
103    c  14000

In [5]:
df2=pd.DataFrame({'ID':[101,102,103],
                  'NAme':['a','b','c'],
                  'SAl':[10000,2000,30000]})
df2

    ID NAme    SAl
0  101    a  10000
1  102    b   2000
2  103    c  30000

In [10]:
dataset=pd.read_csv("C:/Users/Server/OneDrive/Desktop/FBS/data analysis/dataset/Top 10 IT Companies.csv")

In [11]:
dataset

         Top 10 IT Companies
0                        TCS
1                    Infosys
2              Tech Mahindra
3                      Wipro
4           HCL Technologies
5               L&T Infotech
6                   Mindtree
7                    Mphasis
8  Oracle Financial Services
9                Rotla India