In [1]:
import pandas as pd

In [15]:
df2=pd.DataFrame({'ID':[101,102,103],
                  'Name':['abhya','rushi','sahil'],
                  'Sal':[10000,20000,30000]})

In [16]:
df2

    ID   Name    Sal
0  101  abhya  10000
1  102  rushi  20000
2  103  sahil  30000

In [17]:
df2[df2['Sal']>15000]

    ID   Name    Sal
1  102  rushi  20000
2  103  sahil  30000

In [26]:
df2.loc[df2['Sal']<20000,'Sal']=30000

In [27]:
df2

      ID   Name    Sal
0    101  abhya  30000
1  30000  rushi  30000
2  30000  sahil  30000

In [28]:
df=pd.DataFrame({'ID':[101,102,103],
                  'Name':['abhya','rushi','sahil'],
                  'Sal':[10000,20000,30000]})

In [29]:
df

    ID   Name    Sal
0  101  abhya  10000
1  102  rushi  20000
2  103  sahil  30000

In [31]:
df.loc[df['Sal']<20000,'Sal']=15000

In [32]:
df

    ID   Name    Sal
0  101  abhya  15000
1  102  rushi  20000
2  103  sahil  30000

In [33]:
df.loc[[0,2]]

    ID   Name    Sal
0  101  abhya  15000
2  103  sahil  30000

In [34]:
df.loc[[0,2],['ID','Sal']]

    ID    Sal
0  101  15000
2  103  30000

In [37]:
df.loc[[False,True,True]]

    ID   Name    Sal
1  102  rushi  20000
2  103  sahil  30000

In [38]:
df.iloc[0]

ID        101
Name    abhya
Sal     15000
Name: 0, dtype: object

In [39]:
df.iloc[:,[0,2]]

    ID    Sal
0  101  15000
1  102  20000
2  103  30000

In [40]:
df.replace({15000:20000,30000:35000})

    ID   Name    Sal
0  101  abhya  20000
1  102  rushi  20000
2  103  sahil  35000

In [42]:
df['Sal'].replace({15000:15500,30000:35010})

0    15500
1    20000
2    35010
Name: Sal, dtype: int64

In [43]:
df['Sal']=df['Sal'].replace({15000:15500,30000:35050})

In [44]:
df

    ID   Name    Sal
0  101  abhya  15500
1  102  rushi  20000
2  103  sahil  35050

In [46]:
df['Add']=['pune','Mumbai','chennai']

In [47]:
df

    ID   Name    Sal      Add
0  101  abhya  15500     pune
1  102  rushi  20000   Mumbai
2  103  sahil  35050  chennai

In [48]:
df.insert(2,'Age',[21,22,21])

In [49]:
df

    ID   Name  Age    Sal      Add
0  101  abhya   21  15500     pune
1  102  rushi   22  20000   Mumbai
2  103  sahil   21  35050  chennai

In [50]:
df.loc[len(df)]=[104,'Rahul',23,30000,'Delhi']

In [51]:
df

    ID   Name  Age    Sal      Add
0  101  abhya   21  15500     pune
1  102  rushi   22  20000   Mumbai
2  103  sahil   21  35050  chennai
3  104  Rahul   23  30000    Delhi

In [54]:
df.loc[df['Sal']==20000,'Sal']=15000

In [55]:
df

    ID   Name  Age    Sal      Add
0  101  abhya   21  15500     pune
1  102  rushi   22  15000   Mumbai
2  103  sahil   21  35050  chennai
3  104  Rahul   23  30000    Delhi

In [56]:
df.loc[df['ID']==102,'Sal']=15500

In [57]:
df

    ID   Name  Age    Sal      Add
0  101  abhya   21  15500     pune
1  102  rushi   22  15500   Mumbai
2  103  sahil   21  35050  chennai
3  104  Rahul   23  30000    Delhi

In [67]:
df[df['Age']>21]['Name']

1    rushi
3    Rahul
Name: Name, dtype: str

In [68]:
df.loc[df['Age']>21,'Name']

1    rushi
3    Rahul
Name: Name, dtype: str

In [71]:
df[(df['Age']>21) & (df['Sal']>15000)]

    ID   Name  Age    Sal     Add
1  102  rushi   22  15500  Mumbai
3  104  Rahul   23  30000   Delhi

In [72]:
df.drop(3)

    ID   Name  Age    Sal      Add
0  101  abhya   21  15500     pune
1  102  rushi   22  15500   Mumbai
2  103  sahil   21  35050  chennai

In [73]:
df.drop([0,2])

    ID   Name  Age    Sal     Add
1  102  rushi   22  15500  Mumbai
3  104  Rahul   23  30000   Delhi

In [74]:
df.drop('Age',axis=1)

    ID   Name    Sal      Add
0  101  abhya  15500     pune
1  102  rushi  15500   Mumbai
2  103  sahil  35050  chennai
3  104  Rahul  30000    Delhi

In [75]:
data=pd.read_csv("C:/Users/Server/OneDrive/Desktop/FBS/data analysis/dataset/student_10.csv")

In [76]:
mean=data['Study hrs'].mean()

In [77]:
mean

np.float64(4.375)

In [78]:
data['Study hrs'].fillna(mean)

0     2.000
1     6.000
2     3.000
3     0.000
4     4.000
5    10.000
6     4.000
7     4.375
8     4.375
9     6.000
Name: Study hrs, dtype: float64

In [79]:
data.isna()

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [80]:
data.dropna()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
9  12-07-2021      1010.0     12        6.0        85.0

In [81]:
data.isna()

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False

In [82]:
df=data.isna()

In [83]:
df

    Date  Student ID  Class  Study hrs  Percentage
0  False       False  False      False       False
1  False       False  False      False       False
2  False        True  False      False       False
3  False        True  False      False        True
4  False       False  False      False        True
5  False        True  False      False        True
6  False       False  False      False       False
7  False       False  False       True       False
8  False       False  False       True       False
9  False       False  False      False       False